<a href="https://www.kaggle.com/code/ashmitcajla/3-basic-numpy-for-ml?scriptVersionId=234199222" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# 🧠 NumPy: The Ultimate Array Library for Data Science
Welcome to your **interactive NumPy tutorial**! 🎉

NumPy (Numerical Python) is the foundational package for scientific computing in Python. It supports large, multi-dimensional arrays and matrices, along with a wide collection of mathematical functions to operate on these arrays.

Let's dive in and explore the magic of NumPy! 🚀

In [1]:
# Uncomment the line below if NumPy isn't installed already
# !pip install numpy

In [2]:
import numpy as np
print("✅ NumPy is ready to go!")

✅ NumPy is ready to go!


## 📌 Creating NumPy Arrays

In [3]:
# Creating arrays from lists
a = np.array([1, 2, 3])
print("1D Array:", a)

# 2D array (Matrix)
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


## 🔍 Array Attributes

In [4]:
print("Shape:", b.shape)
print("Size:", b.size)
print("Dimensions:", b.ndim)
print("Data Type:", b.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


## 🛠️ Array Initialization Techniques

In [5]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:", arange)
print("Linspace:", linspace)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


## ➕ Element-wise Operations

In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print("Addition:", x + y)
print("Multiplication:", x * y)
print("Power:", x ** 2)

Addition: [11 22 33]
Multiplication: [10 40 90]
Power: [1 4 9]


## 🔎 Indexing and Slicing

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at (1,2):", arr[1, 2])
print("First row:", arr[0])
print("First column:", arr[:, 0])

Element at (1,2): 6
First row: [1 2 3]
First column: [1 4]


## ✅ Boolean Indexing

In [8]:
data = np.array([10, 20, 30, 40, 50])
print("Values > 25:", data[data > 25])

Values > 25: [30 40 50]


## 🔁 Reshaping Arrays

In [9]:
arr = np.arange(12)
print("Original:", arr)
reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 📊 Aggregations and Statistics

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Standard Deviation:", arr.std())

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933


## 🚀 Broadcasting in NumPy

In [11]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print("Broadcasted Sum:\n", a + b)

Broadcasted Sum:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 💾 Saving and Loading Arrays

In [12]:
np.save('my_array.npy', a)
loaded = np.load('my_array.npy')
print("Loaded array:\n", loaded)

Loaded array:
 [[1]
 [2]
 [3]]


## 💡 Did You Know?
- NumPy is the base for almost all scientific libraries in Python like Pandas, SciPy, and Scikit-learn.
- Internally, NumPy is implemented in C for performance.
- It's 50x faster than pure Python lists for numerical computations!
