# DSC ML BOOTCAMP

### DAY 1-2
- Basic Python for ML
- Numpy
- Pandas
- Shutil




---



---

# NumPy

* **Numpy is a general-purpose array processing package. It is the fundamental package for scientific computing using python**

* **It supports large, multi-dimensional arrays and matrices, along with a wide collection of mathematical functions to operate on these arrays.**


🤔 Guess what NumPy stands for ?

### What is an array ?

* An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [ ]:
import numpy as np
print("NumPy is ready to use")

NumPy is ready to use


### Creating my first array in Python 🐍

np.array()

In [ ]:
#creating array using lists
lst = [1,2,3,4,5]




# I can either make a list and then use the name of the list or can create in a single line
b = np.array([1,2,3,4,5])


In [ ]:
print(b)

[1 2 3 4 5]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
a = np.array(lst)
print(a)

[1 2 3 4 5]


In [ ]:
print(b)

[1 2 3 4 5]


In [ ]:
# in python we can verify the type of my entity using type function (inbuilt)

type(a)

In [ ]:
# Array of strings

str_arr = np.array(["akarsh", 'aryan', 'gitesh','tikshan'])

print(str_arr)

['akarsh' 'aryan' 'gitesh' 'tikshan']


## Arrays as we know are of 2 types -
 * 1D Arrays
 * 2D Arrays (Multidimensional Arrays)


#### To see if my array is 1D or 2 D,

*  .ndim function -> returns no. of dimension of the array
*  .shape function -> returns a tuple representing the dimension of the array in the form (m*n)



In [ ]:
a.shape

(5,)

#### Some Useful Array Attributes

* .dtype -> returns the data type of the array contents
* .size() -> returns the total number of elements in the array

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
str_arr.dtype

dtype('<U7')

In [ ]:
arr.size

15

## Creating 2D Arrays or Multinested Arrays


In [ ]:
# we can first make multiple lists and then can use them or can do it in a single line of code

arr  = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
print(arr)
s

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
arr.shape

(3, 5)

In [ ]:
# Now if i run my .size , .ndim ,  .shape functions....
arr.shape

(3, 5)

In [ ]:
arr.ndim

2



---
## *So far we have learnt...*
* making a 1D array
* making a 2D array
* Running some basic attribute checks


---




## Array Initialization Techniques

* np.zeros((m,n))
* np.ones((m,n))
* np.arange(start,stop(Exclusive),step_size) ->create a 1d array with values in a specified range and step size.
* np.linspace(start,stop(inclusive),no._of_points) ->Creates a 1D array with evenly spaced values between two endpoints

## Note -

*  By default, np.zeros creates an array with float data type. If we want we can specify, dtype=int
*  .arange and .linspace will make a 1d array by default but if we want a 2d array we can use the reshape function.

In [ ]:
z_arr = np.zeros((3,3), dtype=int)

In [ ]:
print(z_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
o_arr = np.ones((3,3))

In [ ]:
c = np.arange(10,21,1)
print(c)

[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
d  = np.linspace(10,19, 10 )
print(d)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


## Element Wise Operations
- We can perform operations like addition , subtraction and multiplication etc between arrays



In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [ ]:
print("Addition: ",x+y)
print("Subtraction: ", abs(x-y))
print("Multiplication: ",x*y)
print("Division: ",x/y)
print("Power: ",x**2)

Addition:  [ 7  9 11 13 15]
Subtraction:  [5 5 5 5 5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power:  [ 1  4  9 16 25]




---



---



---



# Reshaping arrays

##### KEY POINTS -

* After reshaping an array, the contents remain the same


In [ ]:
## i have created an array (3*4 dimensions)

arr = np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14]])
print(arr)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


#### Reshape Function

if earlier my array dimensions were m * n then i can reshape my array to some new dimension provided **n * m = m * n**
*  .reshape(m,n)

In [ ]:
# Now i want to reshape this array from 3*4 to say 4*3  then, i will use the .reshape(m,n) function


In [ ]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  6,  7],
       [ 8,  9, 11],
       [12, 13, 14]])

# Indexing in Arrays

* Indexing always starts from Zero


#### For 1D Array



In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
# for a 1D array
print(arr[2])


3


#### For 2D Array

* We can access elements like a[][] in 2d arrays but when diving deep into Python we avoid this.

* We use **Slicing** concept here

In [ ]:
#let's create a 2d array
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## How Slicing Works ?

* arr[_row_ , _col_ ]

* arr[ *start_row : end_row* , *start_col : end_col* ]

*where, **Start row** and **Start col** are **Inclusive** and **End row** and **End col** are **exclusive** .*

#### Note - If end_row or end_col are not specified, it means till the last row and last column (including them)

In [ ]:
print(c[0:2 , 1:3])

[[2 3]
 [6 7]]


In [ ]:
## i want

# [[6 7]
#  [10 11]]

print(c[1:3,1:3])

[[ 6  7]
 [10 11]]


## Boolean Indexing
* like i have a array of height and from it i want to derive/select some bracket of height, so we will go like this height[height> 160]



In [ ]:
bool_arr = np.array([10, 20, 30, 40, 50])


In [ ]:
print("Values > 25:", bool_arr[bool_arr > 25])

Values > 25: [30 40 50]


## Aggregation and Statistics

 * .sum()
 * .mean()
 * .max()
 * .min()
 * .std() -> standard deviation


In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.sum()

np.int64(15)

In [ ]:
arr.mean()

np.float64(3.0)

In [ ]:
arr.max()

np.int64(5)

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.std()

### Copying

* .copy() - inbuilt function
* array[x:y] = z

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr2 = arr.copy()

In [ ]:
print(arr2)

[1 2 3 4 5 6 7 8]


## Tasks for today

* Study BROADCASTING IN numPy

# 💡 Did You Know?

* NumPy is the base for almost all scientific libraries in Python like Pandas, SciPy, and Scikit-learn.
* Internally, NumPy is implemented in C for performance.
* It's 50x faster than pure Python lists for numerical computations!

*for doubts, you can contact -*  

*Agrim Verma*

*8847046566*

*Linkedin -  www.linkedin.com/in/agrimverma11*